### ISSUE TITLE
Automated backups not working

### ISSUE THREAD

**Issue by lafraia** [sameersbn/docker-redmine#170] opened 2016-01-11 19:30 UTC
I see that automated backups look for /usr/bin/redmine-backup-create helper script in order to create the cron job. Looks like this helper script does not exist in the image.

In order to reproduce this you just have to start the image with REDMINE_BACKUP_SCHEDULE set to daily (or any other value).

You also advise against generating a backup on a running instance. How does this work?

**Comment by sameersbn** [comment] 2016-01-12 05:15
p.s. the backups and restore feature is currently only available in the `latest`, `2.6-latest`, `3.0-latest` and `3.1-latest` docker tags. Please use one of these images if you wish to test this feature.

**Comment by lafraia** [comment] 2016-01-13 17:36
Thanks for this great image.

I'm using `3.2.0-2`. Is it ok to downgrate to `latest`? Any plans to upgrade `latest` to 3.2 soon.

**Comment by sameersbn** [comment] 2016-01-14 03:56
the `latest` tag is built from the repo master, which currently is the `3.2` redmine version.

**Comment by lacek** [comment] 2016-01-22 02:44
I am using 3.2.0-3, having the same problem.

Running the backup-create script directly gives error:
```bash
sudo -u redmine /usr/bin/redmine-backup-create
# /usr/bin/redmine-backup-create: line 5: /functions: No such file or directory
```

Then I create a script to tests if the env variables exists:
```bash
echo -e '#!/bin/bash\necho "var: ${REDMINE_RUNTIME_DIR}"\n' > /tmp/test.sh
chmod +x /tmp/test.sh
sudo -u redmine /tmp/test.sh
# var:
```

However, the env variable can be echoed directly:
```bash
sudo -u redmine echo "var ${REDMINE_RUNTIME_DIR}"
# var: /etc/docker-redmine/runtime
```

**Comment by sameersbn** [comment] 2016-01-22 04:17
> sudo -u redmine /usr/bin/redmine-backup-create
> # /usr/bin/redmine-backup-create: line 5: /functions: No such file or directory

You need to preserve the environment

```bash
sudo -HEu redmine /usr/bin/redmine-backup-create
```

or simply execute `/usr/bin/redmine-backup-create` without `sudo`, i.e. `/usr/bin/redmine-backup-create`

**Comment by lacek** [comment] 2016-01-22 05:26
@sameersbn You are right. And I thought the cron job wasn't running because I was running the docker in a VM with timezone different from my local time. I can confirm it working well now.

**Comment by sameersbn** [comment] 2016-01-22 06:59
@lafraia ps. newer tags are now available with this feature. closing this issue. reopen if you face issues.

**Closed by sameersbn** 2016-01-22 06:59 UTC
