### ISSUE TITLE
Redmine 3.0.1 can't create issues?

### ISSUE THREAD

**Issue by DanielBadura** [sameersbn/docker-redmine#92] opened 2015-04-03 15:27 UTC
Hey, i have a little problem with redmine. Is it possible that i can't create an issue with this redmine installation? I have neither the tab "new issue" nor a sidebar option to create a new issue.
I'm stuck with this, i even cant create issues over the redmine api.
I don't know if I have done something horribly wrong or there is a real problem with redmine.

I hope you can help me :/

**Comment by sameersbn** [comment] 2015-04-03 16:18
@DanielBadura check under Administration > Settings > Projects if you have disabled the issues module.
Next, under Project > Settings, check if the issues modules has been disabled.
Lastly, if you are using the redmine tweaks plugin, under Administration > Plugins > Redmine Tweaks, check if you have disabled the Issues module in the multiple select.

If none of this fixes the issue, then remove any plugins you have installed and check. Probably some plugin is causing the issue,

**Comment by DanielBadura** [comment] 2015-04-03 16:22
I don't have the modul in any of these settings. I also have no plugins installed, i have just the plain redmine installation from you.

**Comment by sameersbn** [comment] 2015-04-03 16:44
@DanielBadura I just noticed that the New Issue option is not showing up for me as well

**Comment by DanielBadura** [comment] 2015-04-03 16:46
Nice, so i know I'm not to dump to use your redmine installation :wink:

**Comment by sameersbn** [comment] 2015-04-03 16:53
@DanielBadura I started a fresh and I am now able to see the New Issue button

**Comment by sameersbn** [comment] 2015-04-03 16:58
@DanielBadura I will perform some additional tests tomorrow

**Comment by DanielBadura** [comment] 2015-04-03 17:21
Okey, thanks for your help! :+1:

**Comment by sameersbn** [comment] 2015-04-03 17:25
@DanielBadura However I do believe whatever the case it could be a bug in redmine. If you desire a stable version of redmine you are better off with the 2.6.xx release.

**Comment by aadebuger** [comment] 2015-04-09 14:26
Same question:no new issue button

**Comment by sameersbn** [comment] 2015-04-14 07:51
@DanielBadura @aadebuger I don't exactly know what the issue is. Can you try deleting the `tmp` directory from the data volume and start the container.

**Comment by sameersbn** [comment] 2015-05-06 12:22
@woshihaoren I think i know why this could be happening. I used the following `docker-compose.yml` file to start redmine

```yml
mysql:
  image: sameersbn/mysql:latest
  environment:
    - DB_USER=redmine
    - DB_PASS=password
    - DB_NAME=redmine_production
redmine:
  image: sameersbn/redmine:3.0.2
  links:
    - mysql:mysql
  ports:
    - "18080:80"
```

```bash
docker-compose up
```

This starts redmine with `mysql` and `redmine` in containers and the application is accessible at http://localhost:18080

Once I login as root, If I create a project. There is no "New Issue" tab. This is because, the default configuration was not loaded from the administration page. I have to first visit the "Administration" page and see the below message.

![8207491](https://cloud.githubusercontent.com/assets/410147/7492709/7175ad50-f418-11e4-96ed-1369b38280bd.png)

Here I need to select the "Load Default Configuration".

Now when I create a new project, I can see the "New Issue" button

**Comment by DanielBadura** [comment] 2015-05-06 16:50
Hey, in my installation i dont get this information in the administartion menu.
I looked up how to load redmine default data and found this http://www.redmine.org/projects/redmine/wiki/redmineinstall#Step-7-Database-default-data-set

Maybe you should add this to the image?

**Comment by sameersbn** [comment] 2015-05-06 18:15
@DanielBadura You can already execute raketasks in the image refer https://github.com/sameersbn/docker-redmine#rake-tasks

I will also add this step in future versions of the image so for new installs hopefully this issue will not show.

**Comment by woshihaoren** [comment] 2015-05-07 02:06
Yeah! When I select the "Load Default Configuration". New project can see the  'New Issue' button. Thank you~

**Comment by sameersbn** [comment] 2015-05-07 04:46
@DanielBadura I checked the rake task for loading the default data. It requires that a language is selected for the default data. I cannot make this decision for users. As a result, I will not be adding this step to the image. Instead in the README I will point users to load the default data as per their requirements.

**Comment by sameersbn** [comment] 2015-05-07 04:47
@woshihaoren I am glad you got the issue resolved.

**Comment by woshihaoren** [comment] 2015-05-07 05:17
OK,thanks

**Comment by sameersbn** [comment] 2015-05-07 05:29
@DanielBadura did you get your issue resolved after executing the rake task?

**Comment by sameersbn** [comment] 2015-05-13 06:58
f01a4572344c1398b040eb2e049d182eb2f42cb1 mentions loading of default data

**Comment by sameersbn** [comment] 2015-05-13 07:13
I think this issue can be marked as closed as the issue has been identified and the required steps have been taken

**Closed by sameersbn** 2015-05-13 07:13 UTC

**Comment by amok** [comment] 2016-01-26 09:11
if someone faces same trouble - this helped me https://www.redmine.org/boards/2/topics/46330

**Comment by hcoa** [comment] 2016-02-08 14:43
It is also possible to do via bundle. `bundle exec rake redmine:load_default_data` 
http://www.redmine.org/projects/redmine/wiki/redmineinstall#Step-7-Database-default-data-set

**Comment by amok** [comment] 2016-02-08 15:11
@hcoa it didn't help for me, that's why I've commented about alternative

**Comment by DanielBadura** [comment] 2016-02-08 15:13
@amok loading the default data set should solve your problem. It just creates standard statuses, trackers etc. Did you check if u had tracker etc after exectuing the rake?

**Comment by amok** [comment] 2016-02-08 15:30
@DanielBadura As I remember there were none of standard things you've mentioned (2w have passed - I may be wrong).

**Comment by DanielBadura** [comment] 2016-02-08 15:36
@amok for me has it work and it should just adding the data u need. So i cant think why it doesnt worked for you. Maybe you can try it again with another container? Just to be sure it doesnt work for you.

**Comment by amok** [comment] 2016-02-08 15:50
@DanielBadura when trouble appeared, my redmine users already have done some "magic" with redmine) afraid I can't reproduce same environment with another container

**Comment by sameersbn** [comment] 2016-02-08 16:43
There are 2 things:
 1. Load the default data. This is not done automatically because user can select their language.
 2. You need to enable one or more trackers on your project. Unless trackers are enabled, the "New Issue" button will not show up.

In my experience there is one other reason and that is because of a configuration in the redmine-tweaks plugins. If you have installed this plugin, then please check that you have not disabled the issue tracker modules.

**Comment by AhmerSaeed-SkillOrbit** [comment] 2019-01-11 15:38
@sameersbn i am using your following compose file, but failed to find "New Issue" option

version: '2'

services:
  mysql:
    image: sameersbn/mysql:5.7.22-1
    environment:
    - DB_USER=redmine
    - DB_PASS=
    - DB_NAME=redmine_production
    - MYSQL_ROOT_PASSWORD=
#    - MYSQL_ROOT_HOST=
    ports:
     - 3306:3306
    volumes:
    - /srv/docker/redmine/mysql:/var/lib/mysql
    - /etc/mysql:/etc/mysql

  redmine:
#    build: ./
    image: sameersbn/redmine:3.4.7-1
    depends_on:
    - mysql
    environment:
    - TZ=Asia/Kolkata

    - DB_ADAPTER=mysql2
    - DB_HOST=mysql
    - DB_PORT=3306
    - DB_USER=redmine
    - DB_PASS=
    - DB_NAME=redmine_production

    - REDMINE_PORT=10083
    - REDMINE_HTTPS=false
    - REDMINE_RELATIVE_URL_ROOT=
    - REDMINE_SECRET_TOKEN=

    - REDMINE_SUDO_MODE_ENABLED=false
    - REDMINE_SUDO_MODE_TIMEOUT=15

    - REDMINE_CONCURRENT_UPLOADS=2

    - REDMINE_BACKUP_SCHEDULE=
    - REDMINE_BACKUP_EXPIRY=
    - REDMINE_BACKUP_TIME=

    - SMTP_ENABLED=true
    - SMTP_METHOD=smtp
    - SMTP_DOMAIN=smtpout.asia.secureserver.net
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=465
    - SMTP_USER=azfar.shah@skillorbit.com
    - SMTP_PASS=[thethunder27]
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=:login

#    - IMAP_ENABLED=false
#    - IMAP_HOST=imap.gmail.com
#    - IMAP_PORT=993
#    - IMAP_USER=mailer@example.com
#    - IMAP_PASS=password
#    - IMAP_SSL=true
#    - IMAP_INTERVAL=30

    ports:
    - "10083:80"
    volumes:
    - /srv/docker/redmine/redmine:/home/redmine/data

**Comment by AhmerSaeed-SkillOrbit** [comment] 2019-01-11 15:38
please guide me thanks

**Comment by jcormier** [comment] 2019-01-11 16:52
@AhmerSaeed-SkillOrbit Please don't post on old/closed issues.

Redmine changed the location of the New Issues option, it can be found under the + on the left hand side.

This can be changed back to the original location in settings.
http://www.redmine.org/projects/redmine/wiki/RedmineSettings#Project-menu-tab-for-creating-new-objects
