### ISSUE TITLE
Synology installation failed

### ISSUE THREAD

**Issue by Nan000** [sameersbn/docker-redmine#399] opened 2019-05-06 07:21 UTC
Hi together,

just recently I bought myself a Synology DS218+ NAS and found that it directly supports to install and run redmine from its Package Center. Since this redmine version is not the latest one I came across sameersbn/redmine on dockerhub. I tried to download and install it from the Synology docker GUI but after startup it gives me an database connection error. I've downloaded MariaDB and setup a database along with a user (equipped with the required right) and connected it to docker using the DB_NAME, DB_USER, DB_PASS and so on. Is there anything else I have to do in order to run it?

**Comment by jcormier** [comment] 2019-05-06 13:58
I think if you just go through the different options in the Readme you should be good.

Make sure you mount the data volume somewhere so your data is persistent.

**Comment by jcormier** [comment] 2019-06-03 17:22
Closing due to no resonse

**Comment by Nan000** [comment] 2019-06-13 12:50
Hi jcormier,

sorry for the late response. Here is my problem in detail. I hope you can help me.

I've downloaded and setup the redmine image on my Synology as shown in the screenshot below. Additionally I've created and linked the directory to store redmine's data.

![xxx](https://user-images.githubusercontent.com/34923690/59432770-62248380-8de8-11e9-8f42-5b14a06fcabc.png)

When I start the instance, docker is trying to start everything up but is not able to configure the database as shown in the screenshot below.
  
![xasxas](https://user-images.githubusercontent.com/34923690/59432914-b3cd0e00-8de8-11e9-916e-a65ad4d8954b.png)

I've cross-checked with the default Redmine version (available through the embedded Synology package center) and here an additional file/link to file "mysqld-redmine.sock" is created. I know that database connection information is stored in a .sock files. I've tried to find and open the file to check its content but for some reason its not there. I was only able to locate it when accessing the location using the windows network shared directory. But for some reason the file is 0kB and I'm not able to open it. Might be something like a symlink or so.

![xasxasxasxasx](https://user-images.githubusercontent.com/34923690/59433182-44a3e980-8de9-11e9-9293-c6384ffda3b0.png)

I think I have to link to the database somehow but since I'm not so into the linux/synology topic I'm unable to do so.

I hope you can guide me from here.

Thanks in advanced!

**Comment by jcormier** [comment] 2019-06-13 19:52
> I've cross-checked with the default Redmine version (available through the embedded Synology package center) and here an additional file/link to file "mysqld-redmine.sock" is created. I know that database connection information is stored in a .sock files. I've tried to find and open the file to check its content but for some reason its not there. I was only able to locate it when accessing the location using the windows network shared directory. But for some reason the file is 0kB and I'm not able to open it. Might be something like a symlink or so.

A .sock file is a special file type.
https://askubuntu.com/a/372728/170689

>  I've tried to find and open the file to check its content but for some reason its not there.
How did you look? its possible the GUI hides this file type.

Have you tried just mounting the sock file to the docker?

Also set DEBUG=true which should give you more detailed output about whats failing and post here.

**Comment by Nan000** [comment] 2019-06-16 10:56
Hi jcormier,

thanks for the help.

I was able to fix the database connection issue. I checked the .sock file which was created by the default redmine version and found that it is a symlink pointing to the MarioDB .sock file. The issue here is that the synology DSM won't display symlinks within its File Station and thus I'm unable to select it from the docker-GUI. To work around this I created a dummy file like dummy.sock which I used to created the mount within docker. After that was done I deleted the file and created a second symlink with the same dummy-name pointing to the same MarioDB .sock file.

Unfortunately now I'm running into the following different issue (see log attached). 

**bundler: failed to load command: rake (/usr/bin/rake)**

[redmine-4.0.4.log](https://github.com/sameersbn/docker-redmine/files/3294052/redmine-4.0.4.log)

I hope you can help me here.

Thanks!

**Comment by jcormier** [comment] 2019-06-16 15:29
Hmm could you try this without any plugins installed? Also would help to
see the whole start log possibly with DEBUG=true.

**Comment by Nan000** [comment] 2019-06-17 08:43
Hi,

actually there are no plugins installed. The only think I did is to link a folder to act as redmien's data storage. The folder which where created inside the linked directory by the docker image are untouched.

Anyway, I'll try to enable the DEBUG option later today and post the log.

Thanks for your help!

**Comment by jcormier** [comment] 2019-06-17 13:41
I'd recommend deleting the tmp folder inside the redmine data storage location.

For me that's at /srv/docker/redmine/redmine/tmp/

**Comment by Nan000** [comment] 2019-06-18 05:52
I've deleted the tmp folder with the same result :-(  

Unfortunately I'm unable to run the container in DEBUG mode since I'm starting it from Synology docker GUI.  

To me it still seems like a database access issue since the error appears after the prompt "Migrating database. Please be patient, this could take a while..." I've tested two things:
1.) I've written the password wrongly in purpose within the docker environment vars -> Now docker can't connect to the database anymore.
2.) I've deleted the database which was setup in the docker environment vars -> Same issue as before, Database migration failed.

So somehow docker can access the SQL server but not the database.

**Comment by jcormier** [comment] 2019-06-18 13:20
Hmm this error seems to be jumping out at me.  Perhaps it doesn't like the .sock symlink or something else is symlinked it doesn't like...
```
2019-06-16 10:33:35	stdout	[!] There was an error parsing `Gemfile`: Too many levels of symbolic links - /home/redmine/redmine/vendor/bundle/ruby/2.4.0/specifications. Bundler cannot continue.
```

**Comment by jcormier** [comment] 2019-06-18 15:20
Log of what I ran through to get socket working on my machine.  Maybe it will help you.

```
# Installed postgres on host

 $ sudo su - postgres 
postgres@jcormier-MS-7A93:~$ psql
psql (11.3 (Ubuntu 11.3-1.pgdg18.04+1))
Type "help" for help.
postgres-# \conninfo
You are connected to database "postgres" as user "postgres" via socket in "/var/run/postgresql" at port "5432".
postgres=# \q
postgres@jcormier-MS-7A93:~$ createuser --interactive --pwprompt
Enter name of role to add: redmine
Enter password for new role: 
Enter it again: 
Shall the new role be a superuser? (y/n) n
Shall the new role be allowed to create databases? (y/n) y
Shall the new role be allowed to create more new roles? (y/n) n
postgres@jcormier-MS-7A93:~$ createdb -O redmine redmine
postgres@jcormier-MS-7A93:~$ 


postgres@jcormier-MS-7A93:~$ ls -la /var/run/postgresql*
total 8
drwxrwsr-x  3 postgres postgres  120 Jun 18 10:01 .
drwxr-xr-x 49 root     root     2020 Jun 18 10:01 ..
drwxr-s---  2 postgres postgres   60 Jun 18 10:01 11-main.pg_stat_tmp
-rw-r--r--  1 postgres postgres    6 Jun 18 10:01 11-main.pid
srwxrwxrwx  1 postgres postgres    0 Jun 18 10:01 .s.PGSQL.5432
-rw-------  1 postgres postgres   70 Jun 18 10:01 .s.PGSQL.5432.lock
postgres@jcormier-MS-7A93:~$ file /var/run/postgresql/.s.PGSQL.5432
/var/run/postgresql/.s.PGSQL.5432: socket
postgres@jcormier-MS-7A93:~$ logout

# Create symlink
 $ sudo ln -sf /var/run/postgresql/.s.PGSQL.5432 /var/run/postgresql.sock
 
# Figure out what sock file needs to be named

 $ docker-compose run redmine bash
Creating network "dockerredmine_default" with the default driver
root@d847e86cba0a:/home/redmine/redmine# psql
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
root@d847e86cba0a:/home/redmine/redmine# exit


# Update docker-compose.yml to connect using sock file
 $ git diff
diff --git a/docker-compose.yml b/docker-compose.yml
index c667fb816869..13930057a2c4 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml

   redmine:
     build: ./
     image: sameersbn/redmine:4.0.4
-    depends_on:
-    - postgresql
+    #    depends_on:
+    #    - postgresql
     environment:
     - TZ=Asia/Kolkata
 
     - DB_ADAPTER=postgresql
-    - DB_HOST=postgresql
+    - DB_HOST=localhost
     - DB_PORT=5432
     - DB_USER=redmine
     - DB_PASS=password
@@ -61,3 +61,5 @@ services:
     - "10083:80"
     volumes:
     - /srv/docker/redmine/redmine:/home/redmine/data
+    - /var/run/postgresql.sock:/var/run/postgresql/.s.PGSQL.5432

# Try to connect to database.  But permission issues.
 $ docker-compose run redmine bash
root@dda493495ba8:/home/redmine/redmine# psql -U redmine
psql: FATAL:  Peer authentication failed for user "redmine"
root@dda493495ba8:/home/redmine/redmine# ls -la /var/run/postgresql/.s.PGSQL.5432 
srwxrwxrwx 1 130 138 0 Jun 18 19:31 /var/run/postgresql/.s.PGSQL.5432
root@dda493495ba8:/home/redmine/redmine# exit

# enable password auth for socket, https://stackoverflow.com/a/18664239/780194
 $ sudo vim /etc/postgresql/11/main/pg_hba.conf 
-local   all             all                                     peer
+local   all             all                                     md5
 $ sudo service postgresql restart

# Try again, success
 $ docker-compose run redmine bash
root@5333fe1e5923:/home/redmine/redmine# psql -U redmine
Password for user redmine: 
psql (11.3 (Ubuntu 11.3-1.pgdg16.04+1))
Type "help" for help.

redmine=> 
redmine=> \q
root@5333fe1e5923:/home/redmine/redmine# exit

# Now testing with redmine didn't work, it kept running pg_isready but couldn't find the server.  Its expecting a ip connection.

# Set DB_HOST=/var/run/postgresql which allows pg_isready to pass but then unicorn starts crashing.

redmine_1  | 2019-06-18 20:44:29,998 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
redmine_1  | 2019-06-18 20:44:30,766 INFO exited: unicorn (exit status 1; not expected)
redmine_1  | 2019-06-18 20:44:31,769 INFO spawned: 'unicorn' with pid 233

# Turns out I named the database redmine instead of redmine_production.  Changing DB_NAME to redmine and container starts

 $ docker-compose up
Recreating dockerredmine_redmine_1 ... 
Recreating dockerredmine_redmine_1 ... done
Attaching to dockerredmine_redmine_1
redmine_1  | Initializing logdir...
redmine_1  | Initializing datadir...
redmine_1  | Symlinking dotfiles...
redmine_1  | Installing configuration templates...
redmine_1  | Configuring redmine...
redmine_1  | Configuring redmine::database
redmine_1  | Configuring redmine::unicorn...
redmine_1  | Configuring redmine::secret_token...
redmine_1  | Generating a session token...
redmine_1  | Note:
redmine_1  |   All old sessions will become invalid.
redmine_1  |   Please specify the REDMINE_SECRET_TOKEN parameter for persistence.
redmine_1  |   **SHOULD** be defined if you have a load-balancing Redmine cluster.
redmine_1  | Configuring redmine::max_concurrent_ajax_uploads...
redmine_1  | Configuring redmine::sudo_mode...
redmine_1  | Configuring redmine::autologin_cookie...
redmine_1  | Configuring redmine::backups...
redmine_1  | Configuring nginx...
redmine_1  | Configuring nginx::redmine...
redmine_1  | Installing plugins...
redmine_1  | Installing themes...
redmine_1  | 2019-06-18 20:46:54,413 CRIT Supervisor running as root (no user in config file)
redmine_1  | 2019-06-18 20:46:54,413 WARN Included extra file "/etc/supervisor/conf.d/cron.conf" during parsing
redmine_1  | 2019-06-18 20:46:54,413 WARN Included extra file "/etc/supervisor/conf.d/nginx.conf" during parsing
redmine_1  | 2019-06-18 20:46:54,414 WARN Included extra file "/etc/supervisor/conf.d/unicorn.conf" during parsing
redmine_1  | 2019-06-18 20:46:54,422 INFO RPC interface 'supervisor' initialized
redmine_1  | 2019-06-18 20:46:54,422 CRIT Server 'unix_http_server' running without any HTTP authentication checking
redmine_1  | 2019-06-18 20:46:54,422 INFO supervisord started with pid 1
redmine_1  | 2019-06-18 20:46:55,425 INFO spawned: 'unicorn' with pid 222
redmine_1  | 2019-06-18 20:46:55,428 INFO spawned: 'cron' with pid 223
redmine_1  | 2019-06-18 20:46:55,431 INFO spawned: 'nginx' with pid 224
redmine_1  | 2019-06-18 20:46:56,745 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
redmine_1  | 2019-06-18 20:46:56,745 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
redmine_1  | 2019-06-18 20:46:56,745 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

All the changes to my docker-compose.yml
```diff
 $ git diff
diff --git a/docker-compose.yml b/docker-compose.yml
index c667fb816869..af348bd1f4f5 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -1,29 +1,29 @@
 version: '2'
 
 services:
-  postgresql:
-    image: sameersbn/postgresql:9.6-4
-    environment:
-    - DB_USER=redmine
-    - DB_PASS=password
-    - DB_NAME=redmine_production
-    volumes:
-    - /srv/docker/redmine/postgresql:/var/lib/postgresql
+  #  postgresql:
+  #    image: sameersbn/postgresql:9.6-4
+  #    environment:
+  #    - DB_USER=redmine
+  #    - DB_PASS=password
+  #    - DB_NAME=redmine_production
+  #    volumes:
+  #    - /srv/docker/redmine/postgresql:/var/lib/postgresql
 
   redmine:
     build: ./
     image: sameersbn/redmine:4.0.4
-    depends_on:
-    - postgresql
+    #    depends_on:
+    #    - postgresql
     environment:
     - TZ=Asia/Kolkata
 
     - DB_ADAPTER=postgresql
-    - DB_HOST=postgresql
+    - DB_HOST=/var/run/postgresql
     - DB_PORT=5432
     - DB_USER=redmine
-    - DB_PASS=password
-    - DB_NAME=redmine_production
+    - DB_PASS=redmine
+    - DB_NAME=redmine
 
     - REDMINE_PORT=10083
     - REDMINE_HTTPS=false
@@ -61,3 +61,5 @@ services:
     - "10083:80"
     volumes:
     - /srv/docker/redmine/redmine:/home/redmine/data
+    - /var/run/postgresql.sock:/var/run/postgresql/.s.PGSQL.5432
```

**Comment by SONIC3D** [comment] 2019-08-03 17:35
I have run into same error as @Nan000 met.
It can be reproduce under the following combined condition:
1. DB_ADAPTER=mysql2
2. "/var/run/mysqld/mysqld.sock" not mounted to a file in host filesystem(R/W permission is required for this file).

Detailed description:
I'm running sameersbn/redmine v3.4.6 on my DS218+ fine. And today I decide to migrate to latest sameersbn/redmine latest(4.0.4). Before migrating, I exported the container setting of current v3.4.6 container. Then I clear and deleted the existing container and manually created a new container from sameersbn/redmine latest, and set all parameter in DS218+ Docker system GUI along with the exported setting file.

By referencing the Readme file. I found there is only one directory need to be mounted. So initially I skipped the "/var/run/mysqld/mysqld.sock" mount point in my v3.4.6 exported setting file. I verified the DB connection info is correct and same as the value in backup setting files, but still got error of "Could not connect to database server. Aborting...". I tried to using my DS218+ ip address instead of localhost but not working. Then I found this post. And I see @Nan000 mentioned mounting the mysqld-redmine.sock file which seems not working for him. Then I export the current non-working 4.0.4 container setting and manually edit it to add the additional mount point in "volume_bindings" section:
```
   "volume_bindings" : [
      {
         "host_volume_file" : "/docker/my_redmine_data_path_in_ds218host_path",
         "mount_point" : "/home/redmine/data",
         "type" : "rw"
      },
      {
         "host_volume_file" : "/docker/mysqld/mysqld-redmine.sock",
         "mount_point" : "/var/run/mysqld/mysqld.sock",
         "type" : "rw"
      }
   ],
```

Then remove the previous non-working container and import this modified file and start the container. It seems everything work flawlessly now. And the exist v3.4.6 DB is auto migrated successfully.

<img width="829" alt="屏幕快照 2019-08-04 01 33 26" src="https://user-images.githubusercontent.com/586610/62415172-165bc100-b658-11e9-960e-b0c9e622daf7.png">

**Comment by Nan000** [comment] 2019-08-08 19:01
Hi @SONIC3D,

thanks a lot for sharing your solution. How did you manage to export the original docker redmine settings? When I try this the export-option is grayed out.

![2019-08-08 20_56_38-DS218 - Synology DiskStation](https://user-images.githubusercontent.com/34923690/62730058-86cf5d00-ba1f-11e9-9fe3-18e18f5f3b23.png)

**Comment by stefan-falk** [comment] 2019-11-26 11:10
I had a similar issue.

This is what I did:

- set `DB_TYPE` to `mysql2`
- make sure the password contains no escape characters (idk if that is important but I just wanted to rule this out)
- set `DB_HOST` to the actual IP instead of `localhost`

access the redmine using the port 30002 (as set in the configs) e.g. http://192.168.4.164:30002/

After running you should be able to login with user: `admin` password: `admin`.

**Comment by jlegido** [comment] 2020-03-30 10:09
I guess that in my case it was because of below variable contained a dot:

* DB_HOST: client.example-db

I changed to a dash and it works now:

* DB_HOST: client-example-db

**Comment by jcormier** [comment] 2022-02-09 14:32
Closing due to inactivity

**Closed by jcormier** 2022-02-09 14:32 UTC
Labels: question
