### ISSUE TITLE
Error after docker restart: An error occurred while sending mail (getaddrinfo: Name or service not known)

### ISSUE THREAD

**Issue by arnoldse** [sameersbn/docker-redmine#163] opened 2015-12-30 22:00 UTC
Hi there,
I've managed to install email notifications. However, after a backup (see below), the emailing is not working anymore and I'll get the message above. That's strange, because I did not do anything else ... The same appears once the container is stopped and started again. 
But everything works fine by creating a new container with the settings below..

Any suggestions... Yes, I've checked the issues in other places, but this error shows up after running the script.

Any help would be appreciated!

Peace!

Here's the "backup" script:
    #!/bin/bash
    red="$(date +%Y_%m_%d_%H_%M_%S)_redmine"
    pos="$(date +%Y_%m_%d_%H_%M_%S)_postgresql"
    docker stop redmine
    sleep 10
    docker stop postgresql-redmine
    docker commit -p redmine $red
    docker commit -p postgresql-redmine $pos
    docker save -o ~/$red.tar $red
    docker save -o ~/$pos.tar $pos
    docker start postgresql-redmine
    sleep 10
    docker start redmine

Here's the docker config
  docker run --name=redmine -d \
  --link=postgresql-redmine:postgresql \
  --publish=10083:80 --publish 10445:443 \
  --env='REDMINE_PORT=10445' --env='REDMINE_HTTPS=true' \
  --env='SMTP_ENABLED=true' \
  --env='SMTP_DOMAIN=xxx' \
  --env='SMTP_HOST=xxx' \
  --env='SMTP_USER=xxx' \
  --env='SMTP_PASS=xxx' \
  --env='SMTP_PORT=587' \
  --env='SMTP_STARTTLS=true' \
  --env='SMTP_AUTHENTICATION=:plain' \
  --env='TZ=Europe/Berlin' \
  --restart=on-failure:10 \
  --volume=/srv/docker/redmine/redmine:/home/redmine/data \
  sameersbn/redmine
  
  docker run --name=postgresql-redmine -d \
  --env='DB_NAME=redmine_production' \
  --env='DB_USER=redmine' --env='DB_PASS=xxx' \
  --volume=/srv/docker/redmine/postgresql:/var/lib/postgresql \
  sameersbn/postgresql:9.4-11

**Comment by sameersbn** [comment] 2016-01-01 15:12
The issue may be because of the `docker commit` in your script. I have not tested out your script yet, but in the `latest` version of the image I have added a feature to create and restore backups of the redmine installation. 

Please take a look https://github.com/sameersbn/docker-redmine#creating-backups

**Comment by hermesck** [comment] 2016-02-26 10:25
I can confirm, that I have the same issue, When restarting the container without any other action. When I create new container, everything works, like before.

**Comment by sameersbn** [comment] 2016-02-26 13:24
Please check if the issue is resolved with the `latest` build

**Closed** 2016-02-26 13:24 UTC

**Comment by hermesck** [comment] 2016-02-26 14:03
Tested on `latest` build and issue is fixed. Thank you.
