### ISSUE TITLE
Nginx gives alerts about not being able to read from upstream server

### ISSUE THREAD

**Issue by AKoetsier** [sameersbn/docker-redmine#63] opened 2014-12-10 15:45 UTC
When running the docker with this command:

```
docker run -e DB_HOST=10.0.0.1 -e DB_NAME=redmine -e DB_USER=redmine -e DB_PASS=mypass -e DB_TYPE=mysql -v /tmp/log:/var/log/redmine --name=redmine -it --rm -p 10080:80 -v /var/run/docker.sock:/run/docker.sock -v $(which docker):/bin/docker sameersbn/redmine:2.6.0-1
```

It will stop responding to requests after a few requests. Retrying will eventually return the requested page. Adding -e UNICORN_WORKERS=12 helps a bit but will still throw errors in the nginx logs after a few requests (less than 12). The error I see in the logs is: 

```
2014/12/10 15:32:26 [alert] 124#0: *37 readv() failed (13: Permission denied) while reading upstream, client: 10.0.0.10, server: , request: "GET / HTTP/1.1", upstream: "http://unix:/home/redmine/redmine/tmp/sockets/redmine.socket:/", host: "10.0.0.1:10080"
```

The requests were made using curl and even with 12 workers it will return 'transfer closed with outstanding read data remaining'.

**Comment by sameersbn** [comment] 2015-01-07 10:04
@AKoetsier This might have something to do with 14.10 then. I have see similar issue while using containerized nginx (as a proxy) which talks to an upstream application. There it is a  selinux issue. My quickfix there was to not run nginx containerized and then add the required selinux filters.

**Comment by vabue** [comment] 2015-02-24 05:21
Same issue on 14.04

**Comment by sameersbn** [comment] 2015-02-24 05:33
@vabue Make sure that iptables is enabled. When docker starts a container, it adds iptables rules for the port forwarding to function. This means that iptables is required to to enabled for this configuration to be effective.

**Comment by vabue** [comment] 2015-02-24 06:34
Iptables is ok. Disabling apparmor for docker helped.

**Comment by alex-petrenko** [comment] 2015-10-21 15:38
When I disable apparmor for docker like `aa-disable /etc/apparmor.d/docker` my containers do not start anymore:

`Error response from daemon: Cannot start container database: set apparmor profile docker-default: no such file or directory
FATA[0000] Error: failed to start one or more containers `

**Comment by sameersbn** [comment] 2015-11-01 07:54
not sure what the issue is. can you read up on https://github.com/docker/docker/issues/14396 to see if anything applies to your setup?

**Comment by frank-dspeed** [comment] 2017-07-28 18:30
i close this any subscriber can reopen if that still happens thanks to all

**Closed by frank-dspeed** 2017-07-28 18:30 UTC
