### ISSUE TITLE
Redmine 3.0.2 can't create issues?

### ISSUE THREAD

**Issue by woshihaoren** [sameersbn/docker-redmine#100] opened 2015-05-05 13:09 UTC
I don't see the New Issue button.

**Comment by sameersbn** [comment] 2015-05-05 13:16
@woshihaoren is this a new installation? can you tell me exact steps you followed to setup the image?

**Comment by woshihaoren** [comment] 2015-05-05 13:19
I install redmine use 3.0.2.tar.gz ,it is OK

**Comment by sameersbn** [comment] 2015-05-05 13:21
@woshihaoren i dont understand

**Comment by sameersbn** [comment] 2015-05-05 13:22
@woshihaoren did you upgrade from an older version of redmine or is this a fresh install. Also what database server is being used `mysql` or `postgresql`. Finally have you installed any third party plugins for redmine. If yes, which ones?

**Comment by sameersbn** [comment] 2015-05-05 13:22
Duplicate of #92

**Closed by sameersbn** 2015-05-05 13:22 UTC

**Comment by woshihaoren** [comment] 2015-05-05 13:25
It is fresh install，and used mysql，I don't installed third party plugins

**Comment by sameersbn** [comment] 2015-05-05 13:27
@woshihaoren Thanks for the info. I will try with similar setup. i.e. `redmine:3.0.2` with `mysql` server.

**Comment by woshihaoren** [comment] 2015-05-05 13:28
http://www.redmine.org/projects/redmine/wiki/RedmineInstall
After, I followed this guide, install success, and it can create issues.

**Comment by woshihaoren** [comment] 2015-05-05 13:29
@sameersbn  OK, Thanks~

**Comment by woshihaoren** [comment] 2015-05-05 13:43
system: Centos 6.6
1.# docker pull sameersbn/redmine:latest
2.# mysql create user, create database   (mysql is 5.6)
3.# mysql -H10.255.33.8 -uredmine -p123#x111@#!    (test connect)
4.# docker run --name=redmine -p 10080:80  -v /opt/redmine/data:/home/redmine/data --rm  -e "DB_TYPE=mysql" -e "DB_HOST=10.255.33.8" -e "DB_NAME=redmine_production"  -e "DB_USER=redmine" -e "DB_PASS=123#x111@#!" sameersbn/redmine

**Comment by sameersbn** [comment] 2015-05-05 13:59
@woshihaoren are you running mysql in a container as well? or is it installed on the host?

**Comment by woshihaoren** [comment] 2015-05-06 01:39
It is installed on the host
