### ISSUE TITLE
Unable to start postgresql container

### ISSUE THREAD

**Issue by tcollavo** [sameersbn/docker-redmine#193] opened 2016-05-02 19:39 UTC
Hello,

I started messing around with creating a docker network so my containers could have static IPs and at some point, the postgresql container backing my redmine container died (or I inadvertently stopped it). Issue is I can't get the postgresql container to restart - it dies immediately.

The initial startup command was as follows (followed using the quickstart guide):
docker run --name=postgresql-redmine -d --env='DB_NAME=redmine_production' --env='DB_USER=thisredmine' --env='DB_PASS=<password>' --volume=/srv/docker/redmine/postgresql:/var/lib/postgresql sameersbn/postgresql:9.4-17

My redmine container starts just fine but not the postgresql container. I get the following logs in "docker logs postgresql-redmine":
Examine the log output.
Initializing datadir...
Initializing certdir...
Initializing logdir...
Initializing rundir...
Setting resolv ACLs...
pg_ctl: could not start server
Examine the log output.

If I remove the "volume" argument "--volume=/srv/docker/redmine/postgresql:/var/lib/postgresql" from the run command I can get the image to start just fine, but all my data is missing. I feel like something got messed up with the /srv/docker/redmine/postgresql directory, but I can't figure out what. Here are the contents:

myuser@myserver:/srv/docker/redmine$ ls
postgresql  redmine
myuser@myserver:/srv/docker/redmine$ ls -la
total 16
drwxr-xr-x 4 root            root              4096 Apr  1 00:40 .
drwxr-xr-x 3 root            root              4096 Apr  1 00:37 ..
drwxr-xr-x 3 systemd-resolve systemd-bus-proxy 4096 Apr  1 00:37 postgresql
drwxr-xr-x 8 myuser       myuser         4096 Apr  1 00:40 redmine
myuser@myserver:/srv/docker/redmine$ cd postgresql/
myuser@myserver:/srv/docker/redmine/postgresql$ ls -la
total 12
drwxr-xr-x 3 systemd-resolve systemd-bus-proxy 4096 Apr  1 00:37 .
drwxr-xr-x 4 root            root              4096 Apr  1 00:40 ..
drwxr-xr-x 3 systemd-resolve systemd-bus-proxy 4096 Apr  1 00:37 9.4
myuser@myserver:/srv/docker/redmine/postgresql$

Any advice here? I have no idea how to troubleshoot this. If anyone knows how I could export my data from the existing container and into a new container, that would be great as well.

Thanks,
Travis

**Comment by elpirata15** [comment] 2016-05-02 19:50
Please provide information about your environment.

OS and if you are running docker over the host or within VM.
Docker version

**Comment by janez** [comment] 2016-05-02 19:52
Please provide information about your environment.

OS and if you are running docker over the host or within VM.
Docker version

**Comment by tcollavo** [comment] 2016-05-02 20:29
This is within a VM - uname -a
Linux <hostname> 4.2.0-34-generic #39-Ubuntu SMP Thu Mar 10 22:13:01 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
docker -v
Docker version 1.10.3, build 20f81dd

I'm relatively new to docker...when I was experimenting with networking I started a new postgresql DB container and referenced the volume of the existing container...I'm wondering if some piece of that volume was overwritten by the new container, or something like that.

**Comment by elpirata15** [comment] 2016-05-07 08:39
Try running this command, 

```
docker run --name=postgresql-redmine -d \
  --env='DB_NAME=redmine_production' \
  --env='DB_USER=redmine' --env='DB_PASS=password' \
  --volume=/srv/docker/redmine/postgresql:/var/lib/postgresql \
  sameersbn/postgresql:9.4-21
```

Please note, keep the same db, user and password. I got the same issue and I solved that removing and creating new containers with different configurations. 

Finally I changed to official postgres image due to many issues with sameersbn containers.

**Comment by janez** [comment] 2016-05-07 08:51
Try running this command,

docker run --name=postgresql-redmine -d \
  --env='DB_NAME=redmine_production' \
  --env='DB_USER=redmine' --env='DB_PASS=password' \
  --volume=/srv/docker/redmine/postgresql:/var/lib/postgresql \
  sameersbn/postgresql:9.4-21

Please note, keep the same db, user and password. I got the same issue and I solved that removing and creating new containers with different configurations.

Finally I changed to official postgres image due to many issues with sameersbn containers.

**Comment by sameersbn** [comment] 2016-05-08 07:33
@tcollavo sorry to hear about the issue you are facing. Could you provide steps that will allow us to reproduce the issue? There is definitely some steps that you have executed that broke the container.

@janez can you please tell what issues you faced with the container?

**Comment by frank-dspeed** [comment] 2017-07-29 01:24
Closing as no results and all works at present

**Closed by frank-dspeed** 2017-07-29 01:24 UTC
